## Evaluate Amazon - Disable Interest Ads Feature

In [1]:
from df_utils import load_df
from crawl_ids import CrawlFireTVDisableInterestAds, CrawlFireTVMITM
import matplotlib.pyplot as plt
import seaborn as sns
from ott_leaks import print_leak_stats, remove_ch_name_url_false_positives

In [3]:
limit_ads = load_df(CrawlFireTVDisableInterestAds, "tcp_conn")
vanilla = load_df(CrawlFireTVMITM, "tcp_conn")

limit_ads_reqs = load_df(CrawlFireTVDisableInterestAds, "http_req")
vanilla_reqs = load_df(CrawlFireTVMITM, "http_req")

limit_ads_leaks = load_df(CrawlFireTVDisableInterestAds, "leak")
vanilla_leaks = load_df(CrawlFireTVMITM, "leak")

In [18]:
set(vanilla.domain.unique()).difference(set(limit_ads.domain.unique()))

{u'abc.com',
 u'advertising.com',
 u'agkn.com',
 u'amazoncrl.com',
 u'bbc.com',
 u'crwdcntrl.net',
 u'd3h5bk8iotgjvw.cloudfront.net',
 u'db6vy7amvxmdo.cloudfront.net',
 u'dtvce.com',
 u'dz1vmszs6rjp8.cloudfront.net',
 u'execute-api.us-east-1.amazonaws.com',
 u'images-amazon.com',
 u'llnwd.net',
 u'raw.githubusercontent.com',
 u'researchnow.com',
 u'spectrum.s3.amazonaws.com',
 u'ssl-images-amazon.com',
 u'tubi.video'}

In [17]:
set(limit_ads.domain.unique()).difference(set(vanilla.domain.unique()))

{u'adnxs.com',
 u'criteo.com',
 u'deepsgamestudio.appspot.com',
 u'extremereach.io',
 u'firebaseio.com',
 u'macromill.com',
 u'simplestream.com',
 u'simplestreamcdn.com',
 u'tidaltv.com',
 u'verizon.com',
 u'vzw.com',
 u'xfinity.com'}

In [27]:
len(vanilla), len(limit_ads)

(5282, 4156)

In [31]:
len(vanilla_reqs), len(limit_ads_reqs)

(8895, 8269)

In [32]:
vanilla[vanilla.adblocked].domain.nunique(), limit_ads[limit_ads.adblocked].domain.nunique()

(119, 115)

In [33]:
vanilla.domain.nunique(), limit_ads.domain.nunique()

(268, 262)

In [24]:
len(vanilla[vanilla.adblocked]), len(limit_ads[limit_ads.adblocked])

(2786, 1893)

In [25]:
print_leak_stats(vanilla_leaks)

             ID  Num. of leaks  Num. of channels
0    Android ID            923                69
1  Channel name           1437                20
2         AD ID            269                35
3     Serial No            201                33
4   Device name              8                 4
5           Zip             21                 2
6           MAC             26                 3
7          City             12                 1

In [26]:
print_leak_stats(limit_ads_leaks)

             ID  Num. of leaks  Num. of channels
0    Android ID           1000                65
1  Channel name           1419                20
2         AD ID            218                16
3     Serial No            161                24
4   Device name              5                 2
5           Zip             28                 2
6           MAC             30                 3
7          City             24                 1

In [10]:
from nb_utils import get_popular_domains_from_tcp_conns, make_latex_table, get_popular_domains_from_reqs, get_channels_with_most_domains

In [34]:
get_popular_domains_from_tcp_conns(vanilla, 10)

                                  domain  Num. of channels
20                            amazon.com                86
17                   amazon-adsystem.com                65
18                        amazon-dss.com                55
72                       crashlytics.com                33
25                       amazonvideo.com                26
102                         facebook.com                25
89                       doubleclick.net                23
167                     media-amazon.com                23
101  execute-api.us-east-1.amazonaws.com                21
32                   app-measurement.com                21

In [37]:
get_popular_domains_from_tcp_conns(limit_ads, 25)

                                        domain  Num. of channels
18                                  amazon.com                86
68                             crashlytics.com                33
16                              amazon-dss.com                26
29                         app-measurement.com                22
209                      scorecardresearch.com                20
84                             doubleclick.net                19
118                       google-analytics.com                18
81                                  demdex.net                18
17   amazon-web-app-whitelist.s3.amazonaws.com                14
187                                 omtrdc.net                14
13                                akamaihd.net                14
119                                 google.com                14
7                                 adobedtm.com                13
124                                gstatic.com                13
160                           media-amazon.com                13
6                                    adobe.com                11
95                                facebook.com                11
15                         amazon-adsystem.com                10
133                      imasdk.googleapis.com                10
259                                youtube.com                10
260                                  ytimg.com                10
123                            googlevideo.com                 9
121                      googlesyndication.com                 9
177                               newrelic.com                 8
131                                   ifood.tv                 7

In [5]:
limit_ads_leaks = load_df(CrawlRokuLimitAdTracking, "leak")
vanilla_leaks = load_df(CrawlRokuMITM, "leak")

remove_ch_name_url_false_positives(limit_ads_leaks)  # this is part of the leak detection flow now
remove_ch_name_url_false_positives(vanilla_leaks)  # this is part of the leak detection flow now

In [17]:
get_channels_with_most_domains(limit_ads, head=20)

,channel_name,rank,category,# tracking domains
33,Fox News Channel,35,News & Weather,57
81,Sexy Shorts,215,Special Interest,25
75,Relax My Dog - TV and Music,397,Special Interest,24
58,NBC News,31,News & Weather,15
59,NBC Sports,39,Sports,13
98,iFood.tv,571,Food,12
55,Models In Motion,339,Special Interest,10
57,NBA,80,Sports,10
14,CBS Sports Stream & Watch Live,117,Sports,8
87,TED,204,Educational,8
67,Nickelodeon,58,Kids & Family,8
71,Pluto TV - It's Free TV,11,Movies & TV,8
37,Grindhouse Connection Plus,252,Special Interest,7
15,CNNgo,59,News & Weather,7
46,Indian Recipes by iFood.tv,1065,Food,7
13,CBS News,28,News & Weather,7
6,Babes by Fawesome.tv,263,Special Interest,7
20,CopyKat Recipes,1178,Food,6
26,Dr Sonjia's Sex in South Beach,653,Educational,6
27,ESPN,21,Sports,6

In [18]:
get_channels_with_most_domains(vanilla, head=20)

,channel_name,rank,category,# tracking domains
75,Relax My Dog - TV and Music,397,Special Interest,21
20,CopyKat Recipes,1178,Food,20
58,NBC News,31,News & Weather,17
55,Models In Motion,339,Special Interest,12
15,CNNgo,59,News & Weather,10
59,NBC Sports,39,Sports,10
6,Babes by Fawesome.tv,263,Special Interest,10
99,iFood.tv,571,Food,9
57,NBA,80,Sports,8
87,TED,204,Educational,8
67,Nickelodeon,58,Kids & Family,7
37,Grindhouse Connection Plus,252,Special Interest,7
13,CBS News,28,News & Weather,7
14,CBS Sports Stream & Watch Live,117,Sports,7
7,BabyFirst,408,Educational,7
26,Dr Sonjia's Sex in South Beach,653,Educational,6
1,ABC News,41,News & Weather,6
64,NewsON,36,News & Weather,6
33,Fox News Channel,35,News & Weather,6
97,YouTube TV,9,Movies & TV,5