In [1]:
import LeakDetector
import numpy as np
import pandas as pd
from os.path import isdir, join, basename
from datetime import datetime
from glob import glob

In [6]:
from device_ids import TV_ID_MAP
from log_analysis import get_crawl_parameter
from crawl_ids import CrawlRokuTop1KNoMITM, CrawlRokuTop1KMITM, CrawlFireTVTop1KNoMITM, CrawlFireTVTop1KMITM
from df_utils import load_df
from nb_utils import make_latex_table, get_popular_domains_from_reqs, get_popular_domains_from_tcp_conns
from ott_leaks import run_leak_detection, DEVICE_ID_NAMES, print_leak_stats, remove_ch_name_url_false_positives

## Load leaks
- Run the following to detect and pickle leaks
  - Detect on all crawls: `python2 detect_leaks.py`
  - Detect on a single crawl: `python2 detect_leaks.py roku-data-20190508-013650`

In [12]:
leaks_roku = load_df(CrawlRokuTop1KMITM, "leak")
id_leaks_roku = leaks_roku[leaks_roku.id_type.isin(DEVICE_ID_NAMES)]
nonblocked_id_leaks_roku = id_leaks_roku[~id_leaks_roku.adblocked]

df = get_popular_domains_from_reqs(nonblocked_id_leaks_roku, head=100)
df[df['Num. of channels'] >= 2]

          req_domain  Num. of channels
14        irchan.com                42
18    monarchads.com                40
1          adrise.tv                18
16         kargo.com                16
3    aragoncreek.com                 7
17     lightcast.com                 6
10      ewscloud.com                 5
21    myspotlight.tv                 4
0                                    3
2       akamaihd.net                 3
6         bigstar.tv                 3
7      brightline.tv                 3
20  mtvnservices.com                 2
15    junctiontv.net                 2

In [13]:
top_ott_trackers = df[df['Num. of channels'] > 1].req_domain.unique()

In [15]:
tcp = load_df(CrawlRokuTop1KMITM, "tcp_conn")
req = load_df(CrawlRokuTop1KMITM, "http_req")
get_popular_domains_from_tcp_conns(tcp[tcp.domain.isin(top_ott_trackers)], head=100)
#get_popular_domains_from_reqs(req[req.req_domain.isin(top_ott_trackers)], head=100)

              domain  Num. of channels
1       akamaihd.net                92
6         irchan.com                74
10    monarchads.com                74
5       ewscloud.com                31
8          kargo.com                25
0          adrise.tv                18
2    aragoncreek.com                 7
9      lightcast.com                 7
11  mtvnservices.com                 7
12    myspotlight.tv                 6
3         bigstar.tv                 3
4      brightline.tv                 3
7     junctiontv.net                 2